### ISSUE TITLE
Is this compatible with Jest?

### ISSUE THREAD

**Issue by mjmaix** [cartant/firebase-nightlight#12]
I want to use this on my react-native project and use the built-in Jest testing framework, however I'm getting 

```
    TypeError: fn.call is not a function

      at resolve (node_modules/jest-jasmine2/build/queue_runner.js:46:12)
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
```

at the end of my tests.

I would prepare a simple recreation as soon as possible

**Comment by cartant** [comment]
The library is unopinionated regarding test frameworks and should be compatible with Jest.

I guess it's possible that it could be incompatible with React Native, but I would not have thought it would have touched any APIs that could cause problems and it shouldn't be reliant upon any Node specific `require` behaviours.

This issue needs to include more information. Ideally, a small repo that reproduces the problem.

**Comment by mjmaix** [comment]
I tested and it's working, I figured that I got syntax error somewhere and corrected the issue
Here's the simple app for anyone interested https://github.com/mjmaix/RNFirebaseJest
